### ISSUE TITLE
Feature Info Table, Searchbar cannot be dissabled

### ISSUE THREAD

**Issue by philippfra** [virtualcitySYSTEMS/map-ui#1]
Searchbar in Feature Info Table is always visible. Adding Option {"showSearchbar": false} to the FeaturInfo property don't work.
This line always returns `true`'? https://github.com/virtualcitySYSTEMS/map-ui/blob/4763ab660bd7c03aaa9537fb2ed6dfdeeed30d0f/src/featureInfo/tableFeatureInfoView.js#L65C5-L65C79

this solution worked for me:
```this.showSearchbar = !options.showSearchbar ? options.showSearchbar : defaultOptions.showSearchbar;```
also change the default value to `true`

**Comment by jbo023** [comment]
Hi, thanks for the bugreport, its now fixed in the repository
