### ISSUE TITLE
vcmap mobile: hide useless buttons?

### ISSUE THREAD

**Issue by philippfra** [virtualcitySYSTEMS/map-ui#2]
In mobile view, the tool buttons are invisible. Though the "MyWorkspace" is useless. There is no way, as far as i know, to create an Element in "My Workspace" without using any Tools. In my opinion, the button "My Workspace" should be hidden in mobile view. There are surely further buttons in future, which should be hidden in mobile because they are useless. In my application, I hide this specific button with a hack in the VcsActionButtonList: 
![Bildschirmfoto vom 2024-04-26 11-28-33](https://github.com/virtualcitySYSTEMS/map-ui/assets/111355860/466769be-610d-4f06-8bfc-f1bba65513af)

I suggest to add a property to the  action to specify if a button should be shown or hidden in mobile view. The Vue Element VcsActionList can further be extended with the v-if-clause as my hack above, but instead of the button name it shoud be the new property.

**Comment by MaxHaverkamp** [comment]
>  Though the "MyWorkspace" is useless. There is no way, as far as i know, to create an Element in "My Workspace" without using any Tools.

![image](https://github.com/virtualcitySYSTEMS/map-ui/assets/49388855/bce80f3d-a722-4917-abde-92c1f8b61e37)

"MyWorkspace" offers an import function, so you can import on computer/tablet generated shapes, flights etc., which can be useful and is most likely the reason it is not hidden

**Comment by philippfra** [comment]
I didn't consider the import-function. As I do not need this, I hide the buttons as I proposed above. Thank you.
